IF OBJECT_ID(N'[dbo].[TOOLS_APP_INSTRUMENT_MASTER_DATA]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_APP_INSTRUMENT_MASTER_DATA] (
        [REF_NO] INT NOT NULL,
        [CALIBRATION_DATE] DATETIME NULL,
        [NEXT_CALIBRATION_DUE] DATETIME NULL,
        [OBSERVED_ERROR] NVARCHAR(200) NULL,
        [CALIBRATION_AGENCY] NVARCHAR(100) NULL,
        [UPDATED_AT] DATETIME NOT NULL CONSTRAINT [TOOLS_APP_INSTRUMENT_MASTER_DATA_UPDATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT [TOOLS_APP_INSTRUMENT_MASTER_DATA_pkey] PRIMARY KEY CLUSTERED ([REF_NO]),
        CONSTRAINT [TOOLS_APP_INSTRUMENT_MASTER_DATA_REF_NO_fkey]
          FOREIGN KEY ([REF_NO]) REFERENCES [dbo].[GAUGEANDTOOLS]([REF_NO])
          ON DELETE CASCADE ON UPDATE NO ACTION
    );
END;
