CREATE TABLE [dbo].[TOOLS_APP_CALIBRATION_AGENCY] (
  [ID] INT IDENTITY(1,1) NOT NULL,
  [AGENCY_CODE] NVARCHAR(10) NOT NULL,
  [AGENCY_NAME] NVARCHAR(100) NOT NULL,
  [ADDRESS] NVARCHAR(500) NULL,
  [CONTACT_PERSON] NVARCHAR(100) NULL,
  [PHONE] NVARCHAR(30) NULL,
  [EMAIL] NVARCHAR(150) NULL,
  [ACCREDITATION_NO] NVARCHAR(100) NULL,
  [ACCREDITATION_EXPIRY] DATETIME NULL,
  [CAPABILITIES] NVARCHAR(1000) NULL,
  [IS_AUTHORIZED] BIT NOT NULL CONSTRAINT [DF_TOOLS_CALIB_AGENCY_AUTH] DEFAULT 1,
  [IS_ACTIVE] BIT NOT NULL CONSTRAINT [DF_TOOLS_CALIB_AGENCY_ACTIVE] DEFAULT 1,
  [CREATED_BY] NVARCHAR(50) NOT NULL,
  [CREATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_CALIB_AGENCY_CREATED] DEFAULT GETDATE(),
  [UPDATED_BY] NVARCHAR(50) NULL,
  [UPDATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_CALIB_AGENCY_UPDATED] DEFAULT GETDATE(),
  CONSTRAINT [PK_TOOLS_APP_CALIBRATION_AGENCY] PRIMARY KEY ([ID]),
  CONSTRAINT [UQ_TOOLS_APP_CALIBRATION_AGENCY_CODE] UNIQUE ([AGENCY_CODE])
);

CREATE INDEX [IX_TOOLS_CALIB_AGENCY_ACTIVE_AUTH]
ON [dbo].[TOOLS_APP_CALIBRATION_AGENCY] ([IS_ACTIVE], [IS_AUTHORIZED]);
