CREATE TABLE [TOOLS_APP_NOTIFICATION_SETTING] (
  [ID] INT NOT NULL CONSTRAINT [TOOLS_APP_NOTIFICATION_SETTING_pkey] PRIMARY KEY CONSTRAINT [TOOLS_APP_NOTIFICATION_SETTING_ID_default] DEFAULT 1,
  [ALERT_DAYS] INT NOT NULL CONSTRAINT [TOOLS_APP_NOTIFICATION_SETTING_ALERT_DAYS_default] DEFAULT 15,
  [EMAIL_ENABLED] BIT NOT NULL CONSTRAINT [TOOLS_APP_NOTIFICATION_SETTING_EMAIL_ENABLED_default] DEFAULT 1,
  [SYSTEM_ENABLED] BIT NOT NULL CONSTRAINT [TOOLS_APP_NOTIFICATION_SETTING_SYSTEM_ENABLED_default] DEFAULT 1,
  [UPDATED_BY] NVARCHAR(50), [UPDATED_AT] DATETIME NOT NULL
);
CREATE TABLE [TOOLS_APP_NOTIFICATION_RECIPIENT] (
  [ID] INT NOT NULL IDENTITY(1,1), [NAME] NVARCHAR(100) NOT NULL, [EMAIL] NVARCHAR(150) NOT NULL,
  [UNIT_CODE] NVARCHAR(100), [IS_ACTIVE] BIT NOT NULL CONSTRAINT [TOOLS_APP_NOTIFICATION_RECIPIENT_IS_ACTIVE_default] DEFAULT 1,
  [CREATED_BY] NVARCHAR(50) NOT NULL, [CREATED_AT] DATETIME NOT NULL CONSTRAINT [TOOLS_APP_NOTIFICATION_RECIPIENT_CREATED_AT_default] DEFAULT CURRENT_TIMESTAMP,
  [UPDATED_BY] NVARCHAR(50), [UPDATED_AT] DATETIME NOT NULL,
  CONSTRAINT [TOOLS_APP_NOTIFICATION_RECIPIENT_pkey] PRIMARY KEY ([ID]), CONSTRAINT [TOOLS_APP_NOTIFICATION_RECIPIENT_EMAIL_key] UNIQUE ([EMAIL])
);
CREATE INDEX [TOOLS_APP_NOTIFICATION_RECIPIENT_active_unit_idx] ON [TOOLS_APP_NOTIFICATION_RECIPIENT]([IS_ACTIVE], [UNIT_CODE]);
CREATE TABLE [TOOLS_APP_CALIBRATION_NOTIFICATION] (
  [ID] INT NOT NULL IDENTITY(1,1), [TOOL_OR_GAUGE_NO] NVARCHAR(25) NOT NULL, [UNIT_CODE] NVARCHAR(100),
  [DUE_DATE] DATETIME NOT NULL, [REMINDER_DATE] DATETIME NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_REMINDER_DATE_default] DEFAULT CURRENT_TIMESTAMP,
  [CHANNEL] NVARCHAR(10) NOT NULL, [RECIPIENT_EMAIL] NVARCHAR(150) NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_RECIPIENT_default] DEFAULT '',
  [SUBJECT] NVARCHAR(200) NOT NULL, [MESSAGE] NVARCHAR(1000) NOT NULL,
  [STATUS] NVARCHAR(20) NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_STATUS_default] DEFAULT 'PENDING',
  [SENT_AT] DATETIME, [READ_AT] DATETIME, [ERROR_MESSAGE] NVARCHAR(500),
  [CREATED_AT] DATETIME NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_CREATED_AT_default] DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_pkey] PRIMARY KEY ([ID]),
  CONSTRAINT [TOOLS_APP_NOTIFICATION_DEDUPE] UNIQUE ([TOOL_OR_GAUGE_NO], [UNIT_CODE], [DUE_DATE], [CHANNEL], [RECIPIENT_EMAIL])
);
CREATE INDEX [TOOLS_APP_CALIBRATION_NOTIFICATION_channel_status_idx] ON [TOOLS_APP_CALIBRATION_NOTIFICATION]([CHANNEL], [STATUS], [CREATED_AT]);
INSERT INTO [TOOLS_APP_NOTIFICATION_SETTING] ([ID], [ALERT_DAYS], [EMAIL_ENABLED], [SYSTEM_ENABLED], [UPDATED_AT]) VALUES (1, 15, 1, 1, CURRENT_TIMESTAMP);
