IF COL_LENGTH('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT', 'UNIT_CODE') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_NOTIFICATION_RECIPIENT] ADD [UNIT_CODE] NVARCHAR(100) NULL;

IF COL_LENGTH('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT', 'RESPONSIBILITY') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_NOTIFICATION_RECIPIENT] ADD [RESPONSIBILITY] NVARCHAR(15) NULL;

IF COL_LENGTH('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT', 'CREATED_BY') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_NOTIFICATION_RECIPIENT]
    ADD [CREATED_BY] NVARCHAR(50) NOT NULL
      CONSTRAINT [TOOLS_APP_NOTIFICATION_RECIPIENT_CREATED_BY_default] DEFAULT 'SYSTEM';

IF COL_LENGTH('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT', 'UPDATED_BY') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_NOTIFICATION_RECIPIENT] ADD [UPDATED_BY] NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT', 'UPDATED_AT') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_NOTIFICATION_RECIPIENT]
    ADD [UPDATED_AT] DATETIME NOT NULL
      CONSTRAINT [TOOLS_APP_NOTIFICATION_RECIPIENT_UPDATED_AT_default] DEFAULT CURRENT_TIMESTAMP;

IF COL_LENGTH('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT', 'ROLE') IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM sys.default_constraints dc
    INNER JOIN sys.columns c ON c.default_object_id = dc.object_id
    WHERE dc.parent_object_id = OBJECT_ID('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT')
      AND c.[name] = 'ROLE'
  )
  ALTER TABLE [dbo].[TOOLS_APP_NOTIFICATION_RECIPIENT]
    ADD CONSTRAINT [TOOLS_APP_NOTIFICATION_RECIPIENT_ROLE_default] DEFAULT 'GLOBAL' FOR [ROLE];

IF OBJECT_ID('dbo.TOOLS_APP_CALIBRATION_NOTIFICATION', 'U') IS NULL
BEGIN
  CREATE TABLE [dbo].[TOOLS_APP_CALIBRATION_NOTIFICATION] (
    [ID] INT NOT NULL IDENTITY(1,1),
    [TOOL_OR_GAUGE_NO] NVARCHAR(25) NOT NULL,
    [UNIT_CODE] NVARCHAR(100) NULL,
    [DUE_DATE] DATETIME NOT NULL,
    [REMINDER_DATE] DATETIME NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_REMINDER_DATE_default] DEFAULT CURRENT_TIMESTAMP,
    [CHANNEL] NVARCHAR(10) NOT NULL,
    [RECIPIENT_EMAIL] NVARCHAR(150) NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_RECIPIENT_default] DEFAULT '',
    [RESPONSIBILITY] NVARCHAR(15) NULL,
    [CC_ADDRESS] NVARCHAR(1000) NULL,
    [BCC_ADDRESS] NVARCHAR(1000) NULL,
    [SUBJECT] NVARCHAR(200) NOT NULL,
    [MESSAGE] NVARCHAR(1000) NOT NULL,
    [STATUS] NVARCHAR(20) NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_STATUS_default] DEFAULT 'PENDING',
    [SENT_AT] DATETIME NULL,
    [READ_AT] DATETIME NULL,
    [ERROR_MESSAGE] NVARCHAR(500) NULL,
    [CREATED_AT] DATETIME NOT NULL CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_CREATED_AT_default] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [TOOLS_APP_CALIBRATION_NOTIFICATION_pkey] PRIMARY KEY ([ID])
  );
  CREATE UNIQUE INDEX [TOOLS_APP_NOTIFICATION_DEDUPE]
    ON [dbo].[TOOLS_APP_CALIBRATION_NOTIFICATION]
      ([TOOL_OR_GAUGE_NO], [UNIT_CODE], [DUE_DATE], [CHANNEL], [RECIPIENT_EMAIL]);
  CREATE INDEX [TOOLS_APP_CALIBRATION_NOTIFICATION_channel_status_idx]
    ON [dbo].[TOOLS_APP_CALIBRATION_NOTIFICATION]([CHANNEL], [STATUS], [CREATED_AT]);
END;

IF COL_LENGTH('dbo.TOOLS_APP_CALIBRATION_NOTIFICATION', 'RESPONSIBILITY') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_CALIBRATION_NOTIFICATION] ADD [RESPONSIBILITY] NVARCHAR(15) NULL;

IF COL_LENGTH('dbo.TOOLS_APP_CALIBRATION_NOTIFICATION', 'CC_ADDRESS') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_CALIBRATION_NOTIFICATION] ADD [CC_ADDRESS] NVARCHAR(1000) NULL;

IF COL_LENGTH('dbo.TOOLS_APP_CALIBRATION_NOTIFICATION', 'BCC_ADDRESS') IS NULL
  ALTER TABLE [dbo].[TOOLS_APP_CALIBRATION_NOTIFICATION] ADD [BCC_ADDRESS] NVARCHAR(1000) NULL;

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE [name] = 'TOOLS_APP_NOTIFICATION_RECIPIENT_active_responsibility_idx'
    AND [object_id] = OBJECT_ID('dbo.TOOLS_APP_NOTIFICATION_RECIPIENT')
)
  CREATE INDEX [TOOLS_APP_NOTIFICATION_RECIPIENT_active_responsibility_idx]
    ON [dbo].[TOOLS_APP_NOTIFICATION_RECIPIENT]([IS_ACTIVE], [RESPONSIBILITY]);
