-- Additive baseline for the app-owned module/action RBAC tables.
-- This migration must run after TOOLS_APP_USER exists and before migrations
-- that seed TOOLS_APP_MODULE / TOOLS_APP_ROLE_PERMISSION_MATRIX.

BEGIN TRY
BEGIN TRAN;

IF OBJECT_ID(N'[dbo].[TOOLS_APP_ROLE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_APP_ROLE] (
        [ROLE_ID] INT NOT NULL IDENTITY(1,1),
        [ROLE_NAME] NVARCHAR(50) NOT NULL,
        [IS_SYSTEM_ADMIN] BIT NOT NULL CONSTRAINT [TOOLS_APP_ROLE_IS_SYSTEM_ADMIN_df] DEFAULT 0,
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [TOOLS_APP_ROLE_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
        [UPDATED_AT] DATETIME2 NOT NULL CONSTRAINT [TOOLS_APP_ROLE_UPDATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT [TOOLS_APP_ROLE_pkey] PRIMARY KEY CLUSTERED ([ROLE_ID])
    );
    CREATE UNIQUE NONCLUSTERED INDEX [TOOLS_APP_ROLE_ROLE_NAME_key]
        ON [dbo].[TOOLS_APP_ROLE]([ROLE_NAME]);
END;

IF OBJECT_ID(N'[dbo].[TOOLS_APP_MODULE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_APP_MODULE] (
        [MODULE_ID] INT NOT NULL IDENTITY(1,1),
        [MODULE_KEY] NVARCHAR(50) NOT NULL,
        [MODULE_LABEL] NVARCHAR(100) NOT NULL,
        [MODULE_GROUP] NVARCHAR(50) NOT NULL,
        [APPLICABLE_ACTIONS] NVARCHAR(255) NOT NULL,
        [IS_BUILT] BIT NOT NULL CONSTRAINT [TOOLS_APP_MODULE_IS_BUILT_df] DEFAULT 1,
        [CREATED_AT] DATETIME2 NOT NULL CONSTRAINT [TOOLS_APP_MODULE_CREATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
        [UPDATED_AT] DATETIME2 NOT NULL CONSTRAINT [TOOLS_APP_MODULE_UPDATED_AT_df] DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT [TOOLS_APP_MODULE_pkey] PRIMARY KEY CLUSTERED ([MODULE_ID])
    );
    CREATE UNIQUE NONCLUSTERED INDEX [TOOLS_APP_MODULE_MODULE_KEY_key]
        ON [dbo].[TOOLS_APP_MODULE]([MODULE_KEY]);
END;

IF OBJECT_ID(N'[dbo].[TOOLS_APP_ROLE_PERMISSION_MATRIX]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_APP_ROLE_PERMISSION_MATRIX] (
        [ROLE_ID] INT NOT NULL,
        [MODULE_ID] INT NOT NULL,
        [ACTION] NVARCHAR(30) NOT NULL,
        [ALLOWED] BIT NOT NULL CONSTRAINT [TOOLS_APP_ROLE_PERMISSION_MATRIX_ALLOWED_df] DEFAULT 0,
        CONSTRAINT [TOOLS_APP_ROLE_PERMISSION_MATRIX_pkey]
            PRIMARY KEY CLUSTERED ([ROLE_ID], [MODULE_ID], [ACTION]),
        CONSTRAINT [TOOLS_APP_ROLE_PERMISSION_MATRIX_ROLE_ID_fkey]
            FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[TOOLS_APP_ROLE]([ROLE_ID]) ON DELETE CASCADE,
        CONSTRAINT [TOOLS_APP_ROLE_PERMISSION_MATRIX_MODULE_ID_fkey]
            FOREIGN KEY ([MODULE_ID]) REFERENCES [dbo].[TOOLS_APP_MODULE]([MODULE_ID]) ON DELETE CASCADE
    );
END;

IF OBJECT_ID(N'[dbo].[TOOLS_APP_USER_ROLE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_APP_USER_ROLE] (
        [USER_ID] INT NOT NULL,
        [ROLE_ID] INT NOT NULL,
        CONSTRAINT [TOOLS_APP_USER_ROLE_pkey] PRIMARY KEY CLUSTERED ([USER_ID]),
        CONSTRAINT [TOOLS_APP_USER_ROLE_USER_ID_fkey]
            FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[TOOLS_APP_USER]([id]) ON DELETE CASCADE,
        CONSTRAINT [TOOLS_APP_USER_ROLE_ROLE_ID_fkey]
            FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[TOOLS_APP_ROLE]([ROLE_ID]) ON DELETE CASCADE
    );
END;

IF OBJECT_ID(N'[dbo].[TOOLS_APP_USER_UNIT_SCOPE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_APP_USER_UNIT_SCOPE] (
        [USER_ID] INT NOT NULL,
        [UNIT_SCOPE] NVARCHAR(20) NOT NULL,
        CONSTRAINT [TOOLS_APP_USER_UNIT_SCOPE_pkey] PRIMARY KEY CLUSTERED ([USER_ID], [UNIT_SCOPE]),
        CONSTRAINT [TOOLS_APP_USER_UNIT_SCOPE_USER_ID_fkey]
            FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[TOOLS_APP_USER]([id]) ON DELETE CASCADE
    );
END;

COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    THROW;
END CATCH;
