-- Run against the ORIGINAL ERP database
-- Part 2: Tables that were truncated in previous output

SELECT TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN (
    'OTHER_TOOLS_TYPE',
    'QMS_OTHER_TOOLS_TYPE',
    'TOOLS_DETAILS',
    'TOOLS_MAPPING',
    'TOOLS_MACHINE_TRANS',
    'TOOLS_ISSUE_RECEIVED',
    'TOOLS_ISSUE_RECEIVED_TRANS',
    'TOOLS_CONSUMPTION_TRANS_ISSUE',
    'TOOLS_PO_RECEIVE',
    'TOOLS_PO_RECEIVE_TRANS',
    'TOOLS_PO_SCH_MASTER',
    'TOOLS_ISSUE_FOR_CALIBRATION'
)
ORDER BY TABLE_NAME, ORDINAL_POSITION;
