'use client';

import { useState, useEffect } from 'react';
import { DataTable, FormModal, ConfirmDialog, KPICard, KPIGrid } from '@/components/ui';
import { useModuleStats } from '@/hooks/useModuleStats';
import type { Column, FieldDef } from '@/components/ui';

interface Competency {
  id: number;
  code: string | null;
  name: string;
  category: string;
  type: string | null;
  description: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

interface ApiResponse {
  data: Competency[];
  pagination: { page: number; limit: number; total: number; totalPages: number };
}

interface Requirement {
  id: number;
  competencyId: number;
  departmentId: number | null;
  designationId: number | null;
  gradeId: number | null;
  jobRole: string | null;
  requiredLevelId: number;
  isActive: boolean;
  competency?: { id: number; name: string };
  requiredLevel?: { id: number; levelNumber: number; name: string };
}

interface NamedMaster { id: number; name: string }

// Code is generated by the API (CMP001, CMP002, …) — shown read-only on edit only.
const autoCodeField: FieldDef = { name: 'code', label: 'Code', type: 'text', disabled: true, helpText: 'Generated automatically' };

const fields: FieldDef[] = [
  { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'e.g. React' },
  { name: 'category', label: 'Category', type: 'text', required: true, placeholder: 'e.g. Technical, Behavioral' },
  { name: 'type', label: 'Type', type: 'text', placeholder: 'e.g. Skill, Competency' },
  { name: 'description', label: 'Description', type: 'textarea', placeholder: 'Optional description' },
  { name: 'isActive', label: 'Active', type: 'checkbox', defaultValue: true },
];

export default function CompetencyPage() {
  const [records, setRecords] = useState<Competency[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [pagination, setPagination] = useState({ page: 1, limit: 20, total: 0, totalPages: 0 });
  const [refresh, setRefresh] = useState(0);

  const { stats } = useModuleStats('competencies');

  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [initialValues, setInitialValues] = useState<Record<string, string | number | boolean | undefined>>({});
  const [deleteId, setDeleteId] = useState<number | null>(null);

  // Role Requirements (BRD "required skill/competency" — drives Skill Matrix gaps)
  const [requirements, setRequirements] = useState<Requirement[]>([]);
  const [allCompetencies, setAllCompetencies] = useState<Competency[]>([]);
  const [skillLevels, setSkillLevels] = useState<{ id: number; levelNumber: number; name: string }[]>([]);
  const [departments, setDepartments] = useState<NamedMaster[]>([]);
  const [designations, setDesignations] = useState<NamedMaster[]>([]);
  const [grades, setGrades] = useState<NamedMaster[]>([]);
  const [reqModal, setReqModal] = useState(false);
  const [editReqId, setEditReqId] = useState<number | null>(null);
  const [reqValues, setReqValues] = useState<Record<string, string | number | boolean | undefined>>({});
  const [deleteReqId, setDeleteReqId] = useState<number | null>(null);

  useEffect(() => {
    let mounted = true;
    const load = async () => {
      setLoading(true);
      setError(null);
      try {
        const params = new URLSearchParams({ page: String(page), limit: '20', ...(search ? { search } : {}) });
        const [res, rRes, lRes, dRes, gRes, grRes, allCRes] = await Promise.all([
          fetch(`/api/competencies?${params}`),
          fetch('/api/competency-requirements?limit=200'),
          fetch('/api/skill-levels?limit=50'),
          fetch('/api/masters/departments?limit=200'),
          fetch('/api/masters/designations?limit=200'),
          fetch('/api/masters/grades?limit=200'),
          fetch('/api/competencies?limit=500'),
        ]);
        if (!res.ok) throw new Error('Failed to fetch');
        const json: ApiResponse = await res.json();
        const [rJson, lJson, dJson, gJson, grJson, allCJson] = await Promise.all([rRes.json(), lRes.json(), dRes.json(), gRes.json(), grRes.json(), allCRes.json()]);
        if (!mounted) return;
        setRecords(json.data);
        setPagination(json.pagination);
        setRequirements(Array.isArray(rJson) ? rJson : rJson.data ?? []);
        setAllCompetencies(Array.isArray(allCJson) ? allCJson : allCJson.data ?? []);
        setSkillLevels(Array.isArray(lJson) ? lJson : lJson.data ?? []);
        setDepartments(Array.isArray(dJson) ? dJson : dJson.data ?? []);
        setDesignations(Array.isArray(gJson) ? gJson : gJson.data ?? []);
        setGrades(Array.isArray(grJson) ? grJson : grJson.data ?? []);
      } catch (err) {
        if (!mounted) return;
        setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        if (!mounted) return;
        setLoading(false);
      }
    };
    void load();
    return () => { mounted = false; };
  }, [page, search, refresh]);

  const handleAdd = () => {
    setEditingId(null);
    setInitialValues({ isActive: true });
    setModalOpen(true);
  };

  const handleEdit = (row: Competency) => {
    setEditingId(row.id);
    setInitialValues({
      code: row.code ?? '',
      name: row.name,
      category: row.category,
      type: row.type ?? '',
      description: row.description ?? '',
      isActive: row.isActive,
    });
    setModalOpen(true);
  };

  const handleSubmit = async (values: Record<string, string | number | boolean>) => {
    const payload = {
      ...values,
      type: values.type || null,
      description: values.description || null,
    };

    const url = editingId ? `/api/competencies/${editingId}` : '/api/competencies';
    const method = editingId ? 'PUT' : 'POST';

    const res = await fetch(url, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const err = await res.json();
      throw new Error(err.error ?? 'Save failed');
    }

    setRefresh((n) => n + 1);
  };

  const handleDelete = async (id: number) => {
    const res = await fetch(`/api/competencies/${id}`, { method: 'DELETE' });
    if (!res.ok) {
      const err = await res.json();
      setError(err.error ?? 'Delete failed');
      return;
    }
    setRefresh((n) => n + 1);
  };

  const reqFields: FieldDef[] = [
    { name: 'competencyId', label: 'Competency', type: 'select', required: true, options: allCompetencies.map((c) => ({ label: c.name, value: c.id })) },
    { name: 'departmentId', label: 'Department (blank = all)', type: 'select', options: departments.map((d) => ({ label: d.name, value: d.id })) },
    { name: 'designationId', label: 'Designation (blank = all)', type: 'select', options: designations.map((d) => ({ label: d.name, value: d.id })) },
    { name: 'gradeId', label: 'Grade (blank = all)', type: 'select', options: grades.map((g) => ({ label: g.name, value: g.id })) },
    { name: 'jobRole', label: 'Job Role (blank = all)', type: 'text', placeholder: 'e.g. Machine Operator, Sales Exec' },
    { name: 'requiredLevelId', label: 'Required Level', type: 'select', required: true, options: skillLevels.map((l) => ({ label: `${l.levelNumber} — ${l.name}`, value: l.id })) },
  ];

  const submitRequirement = async (values: Record<string, string | number | boolean>) => {
    const url = editReqId ? `/api/competency-requirements/${editReqId}` : '/api/competency-requirements';
    const res = await fetch(url, {
      method: editReqId ? 'PUT' : 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(values),
    });
    if (!res.ok) throw new Error((await res.json()).error ?? 'Save failed');
    setRefresh((n) => n + 1);
  };

  const deleteRequirement = async (id: number) => {
    const res = await fetch(`/api/competency-requirements/${id}`, { method: 'DELETE' });
    if (!res.ok) {
      setError((await res.json()).error ?? 'Delete failed');
      return;
    }
    setRefresh((n) => n + 1);
  };

  const reqColumns: Column<Requirement>[] = [
    { key: 'competencyId', label: 'Competency', render: (r) => r.competency?.name ?? allCompetencies.find((c) => c.id === r.competencyId)?.name ?? `#${r.competencyId}` },
    { key: 'departmentId', label: 'Department', render: (r) => departments.find((d) => d.id === r.departmentId)?.name ?? 'All' },
    { key: 'designationId', label: 'Designation', render: (r) => designations.find((d) => d.id === r.designationId)?.name ?? 'All' },
    { key: 'gradeId', label: 'Grade', render: (r) => grades.find((g) => g.id === r.gradeId)?.name ?? 'All' },
    { key: 'jobRole', label: 'Job Role', render: (r) => r.jobRole ?? 'All' },
    { key: 'requiredLevelId', label: 'Required Level', render: (r) => r.requiredLevel ? `${r.requiredLevel.levelNumber} — ${r.requiredLevel.name}` : '—' },
  ];

  const columns: Column<Competency>[] = [
    { key: 'code', label: 'Code', render: (row) => row.code ?? '—' },
    { key: 'name', label: 'Name', sortable: true, className: 'font-medium' },
    { key: 'category', label: 'Category' },
    { key: 'type', label: 'Type', render: (row) => row.type ?? '—' },
    { key: 'description', label: 'Description', render: (row) => row.description ?? '—' },
    {
      key: 'isActive',
      label: 'Status',
      render: (row) => (
        <span
          className="rounded-full px-2 py-0.5 text-xs font-medium"
          style={{
            backgroundColor: row.isActive ? '#dcfce7' : '#fee2e2',
            color: row.isActive ? '#166534' : '#991b1b',
          }}
        >
          {row.isActive ? 'Active' : 'Inactive'}
        </span>
      ),
    },
  ];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-semibold" style={{ color: 'var(--foreground)' }}>
          Competency Catalog
        </h1>
        <button
          onClick={handleAdd}
          className="rounded-lg px-4 py-2 text-sm font-medium text-white transition hover:opacity-90"
          style={{ backgroundColor: 'var(--accent)' }}
        >
          + Add Competency
        </button>
      </div>

      <KPIGrid columns={3}>
        <KPICard label="Total Competencies" value={stats.total} tone="info" />
        <KPICard label="Active" value={stats.active ?? 0} tone="success" />
        <KPICard label="Inactive" value={stats.inactive ?? 0} tone="danger" />
      </KPIGrid>

      {error && (
        <div
          className="rounded-lg px-3 py-2 text-sm"
          style={{ backgroundColor: '#fef2f2', color: '#dc2626', border: '1px solid #fecaca' }}
        >
          {error}
        </div>
      )}

      <DataTable
        columns={columns}
        data={records}
        pagination={pagination}
        loading={loading}
        searchValue={search}
        onSearchChange={(v) => {
          setSearch(v);
          setPage(1);
        }}
        onPageChange={setPage}
        onEdit={handleEdit}
        onDelete={(row) => setDeleteId(row.id)}
        searchPlaceholder="Search by name, code or category..."
      />

      <section>
        <div className="mb-2 flex items-center justify-between">
          <h2 className="text-sm font-medium" style={{ color: 'var(--foreground-muted)' }}>
            Role Requirements — which department/designation/grade needs which level (drives Skill Matrix gaps)
          </h2>
          <button
            onClick={() => { setEditReqId(null); setReqValues({}); setReqModal(true); }}
            className="rounded-lg border px-3 py-1.5 text-sm font-medium transition hover:opacity-80"
            style={{ borderColor: 'var(--border)', color: 'var(--foreground)' }}
          >
            + Requirement
          </button>
        </div>
        <DataTable
          columns={reqColumns}
          data={requirements}
          loading={loading}
          emptyMessage="No requirements yet — the Skill Matrix will be empty until you define which roles need which competencies."
          onEdit={(r) => {
            setEditReqId(r.id);
            setReqValues({
              competencyId: r.competencyId,
              departmentId: r.departmentId ?? undefined,
              designationId: r.designationId ?? undefined,
              gradeId: r.gradeId ?? undefined,
              jobRole: r.jobRole ?? undefined,
              requiredLevelId: r.requiredLevelId,
            });
            setReqModal(true);
          }}
          onDelete={(r) => setDeleteReqId(r.id)}
        />
      </section>

      <FormModal
        title={editingId ? 'Edit Competency' : 'Add Competency'}
        fields={editingId ? [autoCodeField, ...fields] : fields}
        initialValues={initialValues}
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        onSubmit={handleSubmit}
        submitLabel={editingId ? 'Update' : 'Create'}
      />

      <ConfirmDialog
        title="Delete Competency"
        message="Are you sure you want to soft-delete this competency?"
        isOpen={deleteId !== null}
        onConfirm={() => deleteId && handleDelete(deleteId)}
        onClose={() => setDeleteId(null)}
      />

      <FormModal
        title={editReqId ? 'Edit Requirement' : 'Add Role Requirement'}
        fields={reqFields}
        initialValues={reqValues}
        isOpen={reqModal}
        onClose={() => setReqModal(false)}
        onSubmit={submitRequirement}
        submitLabel={editReqId ? 'Update' : 'Create'}
      />

      <ConfirmDialog
        title="Delete Requirement"
        message="Remove this role requirement?"
        isOpen={deleteReqId !== null}
        onConfirm={() => deleteReqId && deleteRequirement(deleteReqId)}
        onClose={() => setDeleteReqId(null)}
      />
    </div>
  );
}
