CREATE TABLE [dbo].[TOOLS_APP_INSTRUMENT_DEFECT] (
  [ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [REF_NO] INT NOT NULL,
  [TOOL_OR_GAUGE_NO] NVARCHAR(25) NOT NULL,
  [UNIT_CODE] NVARCHAR(100) NULL,
  [REPORTED_DATE] DATETIME NOT NULL,
  [DEFECT_DETAILS] NVARCHAR(1000) NOT NULL,
  [ERROR_DEVIATION] NVARCHAR(500) NULL,
  [STATUS] NVARCHAR(40) NOT NULL CONSTRAINT [DF_TOOLS_DEFECT_STATUS] DEFAULT N'Defect Reported',
  [DISPOSITION] NVARCHAR(100) NULL,
  [REPORTED_BY] NVARCHAR(50) NOT NULL,
  [CREATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_DEFECT_CREATED] DEFAULT GETDATE(),
  [UPDATED_BY] NVARCHAR(50) NULL,
  [UPDATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_DEFECT_UPDATED] DEFAULT GETDATE(),
  CONSTRAINT [FK_TOOLS_DEFECT_MASTER] FOREIGN KEY ([REF_NO]) REFERENCES [dbo].[GAUGEANDTOOLS]([REF_NO])
);
CREATE INDEX [IX_TOOLS_DEFECT_REF_DATE] ON [dbo].[TOOLS_APP_INSTRUMENT_DEFECT]([REF_NO], [REPORTED_DATE]);
CREATE INDEX [IX_TOOLS_DEFECT_STATUS] ON [dbo].[TOOLS_APP_INSTRUMENT_DEFECT]([STATUS]);

CREATE TABLE [dbo].[TOOLS_APP_INSTRUMENT_SERVICE] (
  [ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [DEFECT_ID] INT NULL,
  [REF_NO] INT NOT NULL,
  [TOOL_OR_GAUGE_NO] NVARCHAR(25) NOT NULL,
  [SERVICE_AGENCY] NVARCHAR(100) NULL,
  [SERVICE_DC_NO] NVARCHAR(30) NULL,
  [SENT_DATE] DATETIME NULL,
  [EXPECTED_RETURN_DATE] DATETIME NULL,
  [RECEIVED_DATE] DATETIME NULL,
  [REPAIR_DETAILS] NVARCHAR(1000) NULL,
  [COST] DECIMAL(18,2) NULL,
  [VERIFICATION_RESULT] NVARCHAR(500) NULL,
  [STATUS] NVARCHAR(40) NOT NULL,
  [FINAL_STATUS] NVARCHAR(40) NULL,
  [CREATED_BY] NVARCHAR(50) NOT NULL,
  [CREATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_SERVICE_CREATED] DEFAULT GETDATE(),
  [UPDATED_BY] NVARCHAR(50) NULL,
  [UPDATED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_SERVICE_UPDATED] DEFAULT GETDATE(),
  CONSTRAINT [FK_TOOLS_SERVICE_DEFECT] FOREIGN KEY ([DEFECT_ID]) REFERENCES [dbo].[TOOLS_APP_INSTRUMENT_DEFECT]([ID]),
  CONSTRAINT [FK_TOOLS_SERVICE_MASTER] FOREIGN KEY ([REF_NO]) REFERENCES [dbo].[GAUGEANDTOOLS]([REF_NO])
);
CREATE INDEX [IX_TOOLS_SERVICE_REF_DATE] ON [dbo].[TOOLS_APP_INSTRUMENT_SERVICE]([REF_NO], [SENT_DATE]);
CREATE INDEX [IX_TOOLS_SERVICE_DEFECT] ON [dbo].[TOOLS_APP_INSTRUMENT_SERVICE]([DEFECT_ID]);
CREATE INDEX [IX_TOOLS_SERVICE_STATUS] ON [dbo].[TOOLS_APP_INSTRUMENT_SERVICE]([STATUS]);

CREATE TABLE [dbo].[TOOLS_APP_CALIBRATION_DEVIATION] (
  [ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [RESULT_ID] INT NULL,
  [ISSUE_LINE_ROW_ID] INT NULL,
  [TOOL_OR_GAUGE_NO] NVARCHAR(25) NOT NULL,
  [PARAMETER] NVARCHAR(100) NOT NULL,
  [EXPECTED_VALUE] NVARCHAR(100) NULL,
  [OBSERVED_VALUE] NVARCHAR(100) NULL,
  [DEVIATION] NVARCHAR(200) NOT NULL,
  [PERMISSIBLE_LIMIT] NVARCHAR(100) NULL,
  [RESULT_STATUS] NVARCHAR(20) NOT NULL,
  [CORRECTIVE_ACTION] NVARCHAR(1000) NULL,
  [RECORDED_BY] NVARCHAR(50) NOT NULL,
  [RECORDED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_DEVIATION_RECORDED] DEFAULT GETDATE(),
  CONSTRAINT [FK_TOOLS_DEVIATION_RESULT] FOREIGN KEY ([RESULT_ID]) REFERENCES [dbo].[TOOLS_APP_CALIBRATION_RESULT]([ID])
);
CREATE INDEX [IX_TOOLS_DEVIATION_TOOL_DATE] ON [dbo].[TOOLS_APP_CALIBRATION_DEVIATION]([TOOL_OR_GAUGE_NO], [RECORDED_AT]);
CREATE INDEX [IX_TOOLS_DEVIATION_RESULT] ON [dbo].[TOOLS_APP_CALIBRATION_DEVIATION]([RESULT_ID]);
