BEGIN TRY
  BEGIN TRANSACTION;

  ALTER TABLE GateNumberRegister ADD remarks NVARCHAR(500) NULL;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
