/* ---------------------------------------------------------------
   ERP master tables — JSON export
   Read-only. NOLOCK is used so nothing on the live ERP is blocked.

   Before running:
     Query > Results To > Results to File          (Ctrl+Shift+F)
     Tools > Options > Query Results > SQL Server > Results to Text
       Maximum characters per column = 8000
   --------------------------------------------------------------- */
USE ERPDB_KUN_HRMS;
GO
SET NOCOUNT ON;
GO

PRINT '--- DEPT ---';
SELECT * FROM DEPT WITH (NOLOCK) FOR JSON PATH;
PRINT '--- CLASS_SUB_DEPT ---';
SELECT * FROM CLASS_SUB_DEPT WITH (NOLOCK) FOR JSON PATH;
PRINT '--- COMPANY_DETAILS ---';
SELECT * FROM COMPANY_DETAILS WITH (NOLOCK) FOR JSON PATH;
PRINT '--- COMPANY_CHILD_UNIT_DETAILS ---';
SELECT * FROM COMPANY_CHILD_UNIT_DETAILS WITH (NOLOCK) FOR JSON PATH;
PRINT '--- STATE_MASTER ---';
SELECT * FROM STATE_MASTER WITH (NOLOCK) FOR JSON PATH;

PRINT '--- HRMS_DESIG_MASTER ---';
SELECT * FROM HRMS_DESIG_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_DESIG_LEVEL_MASTER ---';
SELECT * FROM HRMS_DESIG_LEVEL_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_GRADE_MASTER ---';
SELECT * FROM HRMS_GRADE_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_EMP_CLASS ---';
SELECT * FROM HRMS_EMP_CLASS WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_EMPLOYEE_TYPE_MASTER ---';
SELECT * FROM HRMS_EMPLOYEE_TYPE_MASTER WITH (NOLOCK) FOR JSON PATH;

PRINT '--- HRMS_SHIFT_MASTER ---';
SELECT * FROM HRMS_SHIFT_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_HOLIDAY_MASTER ---';
SELECT * FROM HRMS_HOLIDAY_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_OVERTIME_SLAB ---';
SELECT * FROM HRMS_OVERTIME_SLAB WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_LEAVE_VALIDATE_MASTER ---';
SELECT * FROM HRMS_LEAVE_VALIDATE_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_ATTENDANCE_LOCATION_MASTER ---';
SELECT * FROM HRMS_ATTENDANCE_LOCATION_MASTER WITH (NOLOCK) FOR JSON PATH;

PRINT '--- HRMS_SALARY_COMPONENT ---';
SELECT * FROM HRMS_SALARY_COMPONENT WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_SALARY_LOGIC ---';
SELECT * FROM HRMS_SALARY_LOGIC WITH (NOLOCK) FOR JSON PATH;
PRINT '--- PROF_TAX_SLAP_MASTER ---';
SELECT * FROM PROF_TAX_SLAP_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- TAX_SECTION_MASTER ---';
SELECT * FROM TAX_SECTION_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- TDS_TAX_CODE_MASTER ---';
SELECT * FROM TDS_TAX_CODE_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_LOAN_MASTER ---';
SELECT * FROM HRMS_LOAN_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_COM_BANK_MASTER ---';
SELECT * FROM HRMS_COM_BANK_MASTER WITH (NOLOCK) FOR JSON PATH;

PRINT '--- MULTI_LEVEL_APPROVAL_MASTER ---';
SELECT * FROM MULTI_LEVEL_APPROVAL_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- HRMS_DROPDOWN_MASTER ---';
SELECT * FROM HRMS_DROPDOWN_MASTER WITH (NOLOCK) FOR JSON PATH;
PRINT '--- PROFICIENCY_MASTER ---';
SELECT * FROM PROFICIENCY_MASTER WITH (NOLOCK) FOR JSON PATH;

PRINT '--- SKILL_NAME_DETAILS ---';
SELECT * FROM SKILL_NAME_DETAILS WITH (NOLOCK) FOR JSON PATH;
GO
