-- Tools-owned PO finance tracking (Phase 3).
-- Does NOT alter COMMON_PURCHASE_ORDER / COMMON_PURCHASE_ITEM (shared ERP).
-- GL codes come from existing FINANCE_LEDGER_MASTER (EXP_LEDGER_CODE naming).

BEGIN TRY
BEGIN TRAN;

IF OBJECT_ID(N'[dbo].[TOOLS_PO_FINANCE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_PO_FINANCE] (
        [PO_ORDER_NO] NVARCHAR(16) NOT NULL,
        [PAYMENT_STATUS] NVARCHAR(20) NOT NULL
            CONSTRAINT [TOOLS_PO_FINANCE_payment_status_df] DEFAULT N'UNPAID',
        [PAYMENT_DATE] DATETIME NULL,
        [REMARKS] NVARCHAR(200) NULL,
        [CREAT_USER_ID_CD] NVARCHAR(10) NOT NULL,
        [CREAT_DT] DATETIME NOT NULL,
        [LST_UPDT_USER_ID_CD] NVARCHAR(10) NULL,
        [LST_UPDT_TS] DATETIME NULL,
        CONSTRAINT [TOOLS_PO_FINANCE_pkey] PRIMARY KEY CLUSTERED ([PO_ORDER_NO])
    );
END

IF OBJECT_ID(N'[dbo].[TOOLS_PO_FINANCE_LINE]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[TOOLS_PO_FINANCE_LINE] (
        [ID] INT NOT NULL IDENTITY(1,1),
        [PO_ORDER_NO] NVARCHAR(16) NOT NULL,
        [PO_ITEM_ROW_ID] INT NOT NULL,
        [EXP_LEDGER_CODE] NVARCHAR(25) NULL,
        [BUDGET_CODE] NVARCHAR(50) NULL,
        [CREAT_USER_ID_CD] NVARCHAR(10) NOT NULL,
        [CREAT_DT] DATETIME NOT NULL,
        CONSTRAINT [TOOLS_PO_FINANCE_LINE_pkey] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [TOOLS_PO_FINANCE_LINE_header_fk]
            FOREIGN KEY ([PO_ORDER_NO]) REFERENCES [dbo].[TOOLS_PO_FINANCE]([PO_ORDER_NO])
            ON DELETE CASCADE ON UPDATE NO ACTION
    );

    CREATE UNIQUE NONCLUSTERED INDEX [TOOLS_PO_FINANCE_LINE_item_uid]
        ON [dbo].[TOOLS_PO_FINANCE_LINE]([PO_ITEM_ROW_ID]);

    CREATE NONCLUSTERED INDEX [TOOLS_PO_FINANCE_LINE_po_idx]
        ON [dbo].[TOOLS_PO_FINANCE_LINE]([PO_ORDER_NO]);
END

COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    THROW;
END CATCH;
