-- Additive: Pricing Master approval workflow columns on TOOLS_PRICE_MASTER.
-- Does NOT alter existing RATE values or GRN write targets.

BEGIN TRY
BEGIN TRAN;

IF COL_LENGTH(N'dbo.TOOLS_PRICE_MASTER', N'PROPOSED_RATE') IS NULL
BEGIN
    ALTER TABLE [dbo].[TOOLS_PRICE_MASTER]
        ADD [PROPOSED_RATE] DECIMAL(12, 4) NULL;
END

IF COL_LENGTH(N'dbo.TOOLS_PRICE_MASTER', N'SUBMITTED_BY') IS NULL
BEGIN
    ALTER TABLE [dbo].[TOOLS_PRICE_MASTER]
        ADD [SUBMITTED_BY] NVARCHAR(50) NULL;
END

IF COL_LENGTH(N'dbo.TOOLS_PRICE_MASTER', N'SUBMITTED_AT') IS NULL
BEGIN
    ALTER TABLE [dbo].[TOOLS_PRICE_MASTER]
        ADD [SUBMITTED_AT] DATETIME NULL;
END

IF COL_LENGTH(N'dbo.TOOLS_PRICE_MASTER', N'APPROVED_BY') IS NULL
BEGIN
    ALTER TABLE [dbo].[TOOLS_PRICE_MASTER]
        ADD [APPROVED_BY] NVARCHAR(50) NULL;
END

IF COL_LENGTH(N'dbo.TOOLS_PRICE_MASTER', N'APPROVED_AT') IS NULL
BEGIN
    ALTER TABLE [dbo].[TOOLS_PRICE_MASTER]
        ADD [APPROVED_AT] DATETIME NULL;
END

IF COL_LENGTH(N'dbo.TOOLS_PRICE_MASTER', N'REJECTED_REASON') IS NULL
BEGIN
    ALTER TABLE [dbo].[TOOLS_PRICE_MASTER]
        ADD [REJECTED_REASON] NVARCHAR(500) NULL;
END

-- Existing live rows with blank status → APPROVED so nothing suddenly looks unapproved.
-- Do not overwrite legacy ERP values (Yes/No/Pending/etc.).
UPDATE [dbo].[TOOLS_PRICE_MASTER]
SET [APPROVAL_STATUS] = N'APPROVED'
WHERE [APPROVAL_STATUS] IS NULL
   OR LTRIM(RTRIM([APPROVAL_STATUS])) = N'';

COMMIT TRAN;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    THROW;
END CATCH;
