IF OBJECT_ID(N'[dbo].[TOOLS_APP_CALIBRATION_DEVIATION]', N'U') IS NULL
BEGIN
  CREATE TABLE [dbo].[TOOLS_APP_CALIBRATION_DEVIATION] (
    [ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RESULT_ID] INT NULL,
    [ISSUE_LINE_ROW_ID] INT NULL,
    [TOOL_OR_GAUGE_NO] NVARCHAR(25) NOT NULL,
    [PARAMETER] NVARCHAR(100) NOT NULL,
    [EXPECTED_VALUE] NVARCHAR(100) NULL,
    [OBSERVED_VALUE] NVARCHAR(100) NULL,
    [DEVIATION] NVARCHAR(200) NOT NULL,
    [PERMISSIBLE_LIMIT] NVARCHAR(100) NULL,
    [RESULT_STATUS] NVARCHAR(20) NOT NULL,
    [CORRECTIVE_ACTION] NVARCHAR(1000) NULL,
    [RECORDED_BY] NVARCHAR(50) NOT NULL,
    [RECORDED_AT] DATETIME NOT NULL CONSTRAINT [DF_TOOLS_DEVIATION_RECORDED] DEFAULT GETDATE(),
    CONSTRAINT [FK_TOOLS_DEVIATION_RESULT] FOREIGN KEY ([RESULT_ID]) REFERENCES [dbo].[TOOLS_APP_CALIBRATION_RESULT]([ID])
  );
  CREATE INDEX [IX_TOOLS_DEVIATION_TOOL_DATE] ON [dbo].[TOOLS_APP_CALIBRATION_DEVIATION]([TOOL_OR_GAUGE_NO], [RECORDED_AT]);
  CREATE INDEX [IX_TOOLS_DEVIATION_RESULT] ON [dbo].[TOOLS_APP_CALIBRATION_DEVIATION]([RESULT_ID]);
END;
